name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - dev
    paths:
      - "docs/**"
      - ".github/workflows/sphinx.yml"
      - "langgraph_agent_toolkit/**"
      - "pyproject.toml"
  workflow_dispatch: # Allow manual triggering

# Add permissions to allow GitHub Actions to push to gh-pages
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper versioning

      - name: Create pip cache directory
        run: mkdir -p /home/runner/.cache/pip

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          # Only enable caching if the directory exists
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.2"

      - name: Install dependencies with uv
        run: |
          uv sync --all-extras --frozen --group dev
          uv pip install sphinx-rtd-theme sphinx-pyproject
        env:
          UV_SYSTEM_PYTHON: 1

      - name: Create static directory if it doesn't exist
        run: |
          mkdir -p docs/_static

      - name: Generate API docs
        run: |
          sphinx-apidoc -f -e -M -o docs/generated langgraph_agent_toolkit

      - name: Build documentation
        run: |
          cd docs && sphinx-build -b html . _build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true # Create a single-branch gh-pages
          full_commit_message: "Docs: Update documentation site"
          enable_jekyll: false
