name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - dev
    paths:
      - "docs/**"
      - ".github/workflows/sphinx.yml"
      - "langgraph_agent_toolkit/**"
      - "pyproject.toml"
  workflow_dispatch: # Allow manual triggering

# Add permissions to allow GitHub Actions to push to gh-pages
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper versioning

      - name: Create pip cache directory
        run: mkdir -p /home/runner/.cache/pip

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          # Only enable caching if the directory exists
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.2"

      - name: Install dependencies with uv
        run: |
          # Install the package itself with all dependencies (instead of just installing the dev dependencies)
          uv pip install -e ".[all-llms,all-backends,all-observability]"
          uv pip install sphinx-rtd-theme sphinx-pyproject rootutils
        env:
          UV_SYSTEM_PYTHON: 1

      - name: Verify package installation
        run: |
          python -c "import sys; print('Python:', sys.version)"
          python -c "import langgraph_agent_toolkit; print('Package version:', langgraph_agent_toolkit.__version__)"
          # Check for specific dependencies that are causing import issues
          python -c "import langchain_core; print('langchain_core version:', langchain_core.__version__)"
          python -c "import joblib; print('joblib version:', joblib.__version__)"

      - name: Create static directory if it doesn't exist
        run: |
          mkdir -p docs/_static

      - name: Generate API docs
        run: |
          # Enhanced API documentation generation with better code documentation
          sphinx-apidoc -f -e -o docs/generated langgraph_agent_toolkit \
            --separate \
            --no-toc \
            --no-headings \
            --module-first \
            --doc-project="API Reference"

      - name: Create autosummary template files
        run: |
          mkdir -p docs/_templates/autosummary
          echo '{{ fullname | escape | underline }}

          .. automodule:: {{ fullname }}
             :members:
             :undoc-members:
             :show-inheritance:
             :special-members: __init__' > docs/_templates/autosummary/module.rst

          echo '{{ fullname | escape | underline }}

          .. currentmodule:: {{ module }}

          .. autoclass:: {{ objname }}
             :members:
             :show-inheritance:
             :inherited-members:
             :special-members: __init__
             :undoc-members:' > docs/_templates/autosummary/class.rst

      - name: Build documentation
        run: |
          cd docs && sphinx-build -b html -a -E -v . _build/html
          # The -v flag provides verbose output to see any import errors

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true # Create a single-branch gh-pages
          full_commit_message: "Docs: Update documentation site"
          enable_jekyll: false
